module.exports = {
    dsa: ["LinearSearchList", "BinarySearchList", "TwoCrystalBalls"],
};

// "DFSOnBST",
// "LRU",
// "BubbleSort",
// "SinglyLinkedList",
// "DoublyLinkedList",
// "Queue",
// "Stack",
// "ArrayList",
// "MazeSolver",
// "QuickSort",
// "BTPreOrder",
// "BTInOrder",
// "BTPostOrder",
// "BTBFS",
// "CompareBinaryTrees",
// "DFSOnBST",
// "DFSGraphList",
// "Trie",
// "BFSGraphMatrix",
// "Map",
// "MinHeap",
