module.exports = {
    dsa: [],
};

// "DFSOnBST",
// "LRU",
// "DoublyLinkedList",
// "MazeSolver",
// "QuickSort",
// "BTPreOrder",
// "BTInOrder",
// "BTPostOrder",
// "BTBFS",
// "CompareBinaryTrees",
// "DFSOnBST",
// "DFSGraphList",
// "Trie",
// "BFSGraphMatrix",
// "Map",
// "MinHeap",
